### PR TITLE
Amend changes for CAF FM

### PR DESCRIPTION
**Pull request by LinkBoi00**

### CODE REVIEW

**Comment by gwolf2u** [comment]
looks fine for me
anyone else?

**Comment by neobuddy89** [comment]
Not sure why this is being merged in 12.0 and not 12.1

**Comment by gwolf2u** [comment]
keen eye, didn't saw that one

**Comment by LinkBoi00** [comment]
> Not sure why this is being merged in 12.0 and not 12.1

Because it's not for 12.1, I'll PR there when I get to try it

**Pull request merged**
